let Colors = ['Red', 'green', 'White'];
console.log(Colors);
Colors[2] = 'Black';
console.log(Colors);
console.log(Colors.length);
console.log(Colors.includes('Pink'));
Colors.push('Pink');
console.log(Colors.includes('Pink'));
console.log(Colors);
Colors[2] = 'White';
console.log(Colors);
Colors.unshift('gray');
console.log(Colors);
Colors.shift();
console.log(Colors);
Colors.pop();
console.log(Colors);
console.log(Array.isArray(Colors));
console.log(Colors.includes('Red'));
